version: '3'
services:
  master:
    container_name: master
    hostname: master
    ports:
     - "8089:8089"
     - "5557:5557"
     - "5558:5558"
    image: "grubykarol/locust:0.9.0-python3.6-alpine3.9"
    environment:
      ATTACKED_HOST: http://master:8089
      LOCUST_MODE: master
      LOCUST_MASTER_BIND_PORT: 5557
      TASK_DELAY: 1000
      QUIET_MODE: "${QUIET_MODE:-false}"
    volumes:
      - ./locust-scripts:/locust

  slave:
    image: "grubykarol/locust:0.9.0-python3.6-alpine3.9"
    environment:
      ATTACKED_HOST: http://master:8089
      LOCUST_MODE: slave
      LOCUST_MASTER: master
      LOCUST_MASTER_BIND_PORT: 5557
      NO_PROXY: master
      TASK_DELAY: 1000
      QUIET_MODE: "${QUIET_MODE:-false}"
    volumes:
      - ./locust-scripts:/locust

  standalone:
    image: "grubykarol/locust:0.9.0-python3.6-alpine3.9"
    container_name: standalone
    hostname: standalone
    ports:
     - "8189:8189"
    environment:
      ATTACKED_HOST: http://standalone:8189
      LOCUST_MODE: standalone
      NO_PROXY: standalone
      TASK_DELAY: 1000
      QUIET_MODE: "${QUIET_MODE:-false}"
      LOCUST_OPTS: "--web-port 8189"
    volumes:
      - ./locust-scripts:/locust
