version: '3'
services:
  master:
    container_name: master
    hostname: master
    image: "grubykarol/locust:0.9.0-python3.6-alpine3.9"
    environment:
      ATTACKED_HOST: http://sut
      LOCUST_MODE: master
      LOCUST_MASTER_BIND_PORT: 5557
      FEEDER_BIND_PORT: 5555
      TASK_DELAY: 100
      QUIET_MODE: "${QUIET_MODE:-false}"
      LOCUST_OPTS: "--no-web --expect-slaves 1 -c 1 -r 1 -t 10s"
    volumes:
      - ./locust-scripts:/locust

  slave:
    image: "grubykarol/locust:0.9.0-python3.6-alpine3.9"
    environment:
      ATTACKED_HOST: http://sut
      LOCUST_MODE: slave
      LOCUST_MASTER: master
      LOCUST_MASTER_BIND_PORT: 5557
      FEEDER_HOST: master
      FEEDER_BIND_PORT: 5555
      TASK_DELAY: 100
      QUIET_MODE: "${QUIET_MODE:-false}"
      LOCUST_OPTS: "--no-web"
      NO_PROXY: master
    volumes:
      - ./locust-scripts:/locust

  standalone:
    image: "grubykarol/locust:0.9.0-python3.6-alpine3.9"
    container_name: standalone
    hostname: standalone
    environment:
      ATTACKED_HOST: http://sut
      LOCUST_MODE: standalone
      FEEDER_HOST: standalone
      FEEDER_BIND_PORT: 5555
      TASK_DELAY: 100
      QUIET_MODE: "${QUIET_MODE:-false}"
      LOCUST_OPTS: "--no-web -c 10 -r 10 -t 10s"
      NO_PROXY: standalone
    volumes:
      - ./locust-scripts:/locust

  # test endpoint
  httpbin:
    image: "kennethreitz/httpbin"
    container_name: httpbin
    hostname: httpbin
  sut:
    image: "lucascimon/nginx-logging-proxy"
    container_name: sut
    hostname: sut
    environment:
      PROXIED_ENDPOINT: http://httpbin:80
      LISTENING_PORT: 80
    ports:
      - "80:80"
